name: RSpec
on: [push]

jobs:
  build:
    name: Greeting
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Ruby 2.5.3
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.5.3
    - name: Test with RSpec
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
        bundle exec appraisal install
        bundle exec appraisal rspec
